version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    ports:
      - "8181:8000"
    volumes:
      - .:/var/www/html
    working_dir: /car/www/html
    command: php artisan serve --host=0.0.0.0 --port=8800
    environment:
      - APP_ENV=local
      - APP_KEY=base64:PMBLoCnVbm24Dq40IcrM6tcsBLc5eSQtXXYGnHSBRvg=
      - APP_DEBUG=true
      - APP_URL=http://192.168.1.84:8181
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=pruebacollectr
      - DB_USERNAME=root
      - DB_PASSWORD=toor
    networks:
      - laravel_network

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: pruebacollectr
      MYSQL_USER: root
      MYSQL_PASSWORD: toor
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: toor
    depends_on:
      - db
    networks:
      - laravel_network

volumes:
  db_data:

networks:
  laravel_network:
    driver: bridge
